tiagosiebler/okx-api

- README.md
- package-lock.json
- package.json
- test/private.write.test.ts
> fix readme mistakes

- README.md
- package.json
> v1.0.1: chore() fix readme bullet separator

- README.md
- package.json
- src/rest-client.ts
- test/private.read.test.ts
- test/private.write.test.ts
> v1.0.2: fix strict api response message tests. add missing parameter for loan borrow endpoint.

- package.json
- src/types/rest/request/funding.ts
> v1.0.3: fix(#13): typo in FundsTransferRequest interface

- README.md
- examples/ws-public.ts
- package.json
- src/types/websockets/request.ts
- test/private.read.test.ts
> v1.0.4: feat() add new liquidation orders ws channel

- package.json
v1.0.5, feat(#18): add missing types & properties
> v1.0.5, feat(#18): add missing types & properties

- package-lock.json
- package.json
- src/types/shared.ts
- src/util/websocket-util.ts
- Refer to the following for more information: https://www.okx.com/help-center/changes-to-v5-api-websocket-subscription-parameter-and-url
> v1.0.7: feat() add support for business wss endpoints

- examples/rest-private-trade.ts
- examples/rest-public.ts
- package.json
- src/rest-client.ts
- src/types/websockets/request.ts
- src/util/websocket-util.ts
- test/private.read.test.ts
- test/private.write.test.ts
- test/response.util.ts
> v1.1.3: feat() use any instead of unknown for simpler typing on untyped params

- package.json
- test/private.read.test.ts
- test/private.write.test.ts
> v1.1.4: type fixes

- package.json
- src/rest-client.ts
- test/private.write.test.ts
> v1.1.7: fix import error

- README.md
- package-lock.json
- package.json
- src/rest-client.ts
- Old endpoints are being deprecated soon, this updates these savings endpoints with their replacements: https://www.okx.com/docs-v5/log_en/#upcoming-changes-savings-endpoints-migration
> v1.2.0: feat() update savings endpoints

- package.json
- src/rest-client.ts
- src/types/rest/request/index.ts
- src/types/rest/request/public.ts
- src/types/rest/response/public-data.ts
Added support for the economic calendar endpoint and added some types
> v1.3.1: chore: economic calendar endpoint and types

- package.json
- src/rest-client.ts
- src/types/rest/request/account.ts
- src/types/rest/request/funding.ts
- src/types/rest/response/private-account.ts
- src/types/rest/response/public-data.ts
- src/types/rest/shared.ts
Its me again, added more types and endpoints. Should hopefully be good to go, learned from yesterday :)
Currently working a lot with the library so might find/need more stuff the coming days but then I will release my own package
for my development process to not bump through versions here that fast and will submit bigger PRs then once in a while.
> v1.3.2: chore() support more endpoints and types

- package-lock.json
- package.json
- src/util/requestUtils.ts
update AWS RestBaseUrl domain 
[OKX API Notice](https://www.okx.com/docs-v5/log_en/#upcoming-changes-notice-regarding-the-decommissioning-of-old-okx-domain-names)
> aws REST address update

- package-lock.json
- package.json
- src/rest-client.ts
- src/types/rest/response/private-account.ts
- src/types/rest/shared.ts
1. Add "Set account mode" request https://www.okx.com/docs-v5/en/#trading-account-rest-api-set-account-mode
2. Add "Set auto loan" request https://www.okx.com/docs-v5/en/#trading-account-rest-api-set-auto-loan
> Add methods Set account mode, Set auto loan

- package-lock.json
- package.json
- src/rest-client.ts
- src/types/rest/request/account.ts
- src/types/rest/request/block-trading.ts
- src/types/rest/request/copy-trading.ts
- src/types/rest/request/funding.ts
- src/types/rest/request/grid-trading.ts
- src/types/rest/request/index.ts
- src/types/rest/request/public.ts
- src/types/rest/request/recurring-buy.ts
- src/types/rest/request/signal-bot.ts
- src/types/rest/request/simple-earn.ts
- src/types/rest/request/spread-trading.ts
- src/types/rest/request/subaccount.ts
- src/types/rest/request/trade.ts
- src/types/rest/response/index.ts
- src/types/rest/response/private-account.ts
- src/types/rest/response/private-block-trading.ts
- src/types/rest/response/private-copy-trading.ts
- src/types/rest/response/private-funding.ts
- src/types/rest/response/private-recurring-buy.ts
- src/types/rest/response/private-signal-bot.ts
- src/types/rest/response/private-spread-trading.ts
- src/types/rest/response/private-subaccount.ts
- src/types/rest/response/private-trade.ts
- src/types/rest/response/public-data.ts
- test/public.test.ts
> v1.4.0: feat(): Added New endpoints as of 4th July, 2024

- .gitignore
- package-lock.json
- package.json
- src/rest-client.ts
- src/types/rest/request/grid-trading.ts
- src/types/rest/request/trade.ts
- src/types/rest/response/private-account.ts
- src/types/rest/response/private-recurring-buy.ts
- src/types/rest/response/public-data.ts
> feat(): Added new endpoints, updated request params, marked deprecated field

- docs/endpointFunctionList.md
- package-lock.json
- package.json
- src/rest-client.ts
- src/types/rest/request/grid-trading.ts
- src/types/rest/response/private-account.ts
- src/types/rest/response/private-spread-trading.ts
- src/types/rest/response/private-subaccount.ts
feat(): added new endpoints, updated types
> v1.4.4 feat(): added new endpoints, updated types

- .github/workflows/templates-readme.yml
- README.md
> feat(): added automatic Readme actions

- package-lock.json
- package.json
> v1.4.5: chore() bump audit dependencies

- .github/workflows/e2etest.yml
- test/private.read.test.ts
> fix(): test error code

- test/private.read.test.ts
> chore(): skip fussy tests

- examples/ws-private-handle-auth-fail.ts
- package-lock.json
- package.json
> chore(v1.4.12): bump dependencies, add example for #83.

- package-lock.json
- package.json
- src/rest-client.ts
> chore(): marked fn deprecated

- package.json
- src/types/rest/response/public-data.ts
https://www.okx.com/docs-v5/en/#public-data-rest-api-get-instruments
> fix(types): correct prop name settCcy to settleCcy in Instrument

- package-lock.json
- package.json
- src/util/websocket-util.ts
- src/websocket-client.ts
- test/public.test.ts
Used this. scope in function which lead to undefined. 
Fixed by changing it to provide its own logger in getWsURL function.
> fix(v1.5.3): fixed logger scope in Websocket-util.ts,

- package-lock.json
- package.json
- src/types/rest/response/private-trade.ts
> feat(v1.5.4): added timestamp to submitOrder() response

- package-lock.json
- package.json
- src/util/BaseRestClient.ts
- src/util/browser-support.ts
> fix(v1.5.5): missing await & correct encoding for web crypto api sign

- package-lock.json
- package.json
- src/util/websocket-util.ts
- src/websocket-client.ts
> feat(v1.5.6): add safeTerminate method with fallback for browsers

- package-lock.json
- package.json
- src/types/rest/response/private-account.ts
> feat(v1.5.7): add missing upl property

- package-lock.json
- package.json
- src/types/websockets/request.ts
- src/util/websocket-util.ts
> fix(#106): added candle1s to websocket req types

- examples/demo-trading.ts
feat(): added okx demo trading example
> feat(): added okx demo trading example

- docs/endpointFunctionList.md
- examples/apidoc/RestClient/getAccountCollateralAssets.js
- examples/apidoc/RestClient/setAccountCollateralAssets.js
- package-lock.json
- package.json
- src/rest-client.ts
- src/types/rest/response/private-account.ts
feat(v2.0.3): Added account collateral endpoints
> feat(v2.0.3): Added account collateral endpoints

- examples/rest-private-trade-market.ts
- examples/rest-public.ts
- examples/ws-private-handle-auth-fail.ts
- examples/ws-private.ts
- package-lock.json
- package.json
- src/rest-client.ts
> fix(v2.0.4): optional req params when all properties are optional. fix(#114) public example syntax

- README.md
- examples/rest-private-trade-market.ts
- examples/rest-private-trade.ts
- examples/ws-private.ts
- package-lock.json
- package.json
v2.0.5 chore(): updated readme, updated examples
> chore(): updated readme, updated examples 

- .gitignore
- README.md
- llms.txt
- package-lock.json
- package.json
- tsconfig.json
> chore(v2.0.7): add llms.txt, update tsconfig, bumpd dependencies

- README.md
- docs/endpointFunctionList.md
- examples/apidoc/WebsocketAPIClient/amendMultipleOrders.js
- examples/apidoc/WebsocketAPIClient/amendOrder.js
- examples/apidoc/WebsocketAPIClient/amendSpreadOrder.js
- examples/apidoc/WebsocketAPIClient/cancelMultipleOrders.js
- examples/apidoc/WebsocketAPIClient/cancelOrder.js
- examples/apidoc/WebsocketAPIClient/cancelSpreadOrder.js
- examples/apidoc/WebsocketAPIClient/massCancelOrders.js
- examples/apidoc/WebsocketAPIClient/massCancelSpreadOrders.js
- examples/apidoc/WebsocketAPIClient/submitMultipleOrders.js
- examples/apidoc/WebsocketAPIClient/submitNewOrder.js
- examples/apidoc/WebsocketAPIClient/submitSpreadOrder.js
- llms.txt
> Update endpoint map & llms

- package-lock.json
- package.json
- src/types/websockets/ws-api.ts
> fix(v3.0.4, #135): ws api response data generic

- docs/endpointFunctionList.md
- examples/apidoc/RestClient/setFeeType.js
- examples/apidoc/RestClient/setSettleCurrency.js
- package-lock.json
- package.json
- src/rest-client.ts
- src/types/rest/request/account.ts
- src/types/rest/request/block-trading.ts
- src/types/rest/request/trade.ts
- src/types/rest/response/private-account.ts
- src/types/rest/response/private-block-trading.ts
- src/types/rest/response/public-data.ts
> feat(v3.0.7): Expand RFQ types and settle/fee endpoints
